"""Domain model of rkgk.

The vocabulary and the entities are versioned together: index manifests record `DOMAIN_MODEL_VERSION`,
so an index built with an older model can be detected and rebuilt.
"""

from rkgk.domain.base import SLUG_PATTERN, Entity, Slug
from rkgk.domain.chunk import Chunk
from rkgk.domain.extraction import (
    EXTRACTION_SCHEMA_VERSION,
    LOCAL_CONCEPT_ID_PATTERN,
    ExtractedConcept,
    ExtractedConceptEdge,
    ExtractedEvidence,
    ExtractedPaperConceptEdge,
    ExtractionIssue,
    ExtractionResult,
    ExtractionValidationError,
    LocalConceptId,
    build_extraction_schema,
    check_extraction_against_paper,
    normalize_whitespace,
)
from rkgk.domain.graph import Concept, ConceptEdge, Evidence, PaperConceptEdge
from rkgk.domain.paper import (
    MARKER_PATTERN,
    MarkerKind,
    Page,
    PageMarker,
    Paper,
    PaperIndexEntry,
    PaperMeta,
    PaperPreprocessInfo,
    build_paper_dir_name,
    parse_page,
)
from rkgk.domain.repositories import (
    ExtractionArtifactInvalidError,
    ExtractionArtifactUnreadableError,
    ExtractionNotFoundError,
    ExtractionRepository,
    ExtractionRepositoryError,
    PaperArtifactInvalidError,
    PaperArtifactUnreadableError,
    PaperNotFoundError,
    PaperRepository,
    PaperRepositoryError,
)
from rkgk.domain.vocabulary import (
    ConceptRelationSpec,
    ConceptRelationType,
    ConceptType,
    ConceptTypeSpec,
    Origin,
    OriginSpec,
    PaperConceptRelation,
    RelationSpec,
    describe_vocabulary,
    traversable_concept_relations,
    traversable_concept_types,
    traversable_paper_relations,
)

DOMAIN_MODEL_VERSION = 1

__all__ = [
    "DOMAIN_MODEL_VERSION",
    "EXTRACTION_SCHEMA_VERSION",
    "LOCAL_CONCEPT_ID_PATTERN",
    "MARKER_PATTERN",
    "SLUG_PATTERN",
    "Chunk",
    "Concept",
    "ConceptEdge",
    "ConceptRelationSpec",
    "ConceptRelationType",
    "ConceptType",
    "ConceptTypeSpec",
    "Entity",
    "Evidence",
    "ExtractedConcept",
    "ExtractedConceptEdge",
    "ExtractedEvidence",
    "ExtractedPaperConceptEdge",
    "ExtractionArtifactInvalidError",
    "ExtractionArtifactUnreadableError",
    "ExtractionIssue",
    "ExtractionNotFoundError",
    "ExtractionRepository",
    "ExtractionRepositoryError",
    "ExtractionResult",
    "ExtractionValidationError",
    "LocalConceptId",
    "MarkerKind",
    "Origin",
    "OriginSpec",
    "Page",
    "PageMarker",
    "Paper",
    "PaperConceptEdge",
    "PaperConceptRelation",
    "PaperIndexEntry",
    "PaperMeta",
    "PaperPreprocessInfo",
    "PaperArtifactInvalidError",
    "PaperArtifactUnreadableError",
    "PaperNotFoundError",
    "PaperRepository",
    "PaperRepositoryError",
    "RelationSpec",
    "Slug",
    "build_extraction_schema",
    "build_paper_dir_name",
    "check_extraction_against_paper",
    "describe_vocabulary",
    "normalize_whitespace",
    "parse_page",
    "traversable_concept_relations",
    "traversable_concept_types",
    "traversable_paper_relations",
]
