"""Domain model of rkgk.

The vocabulary and the entities are versioned together: index manifests record `DOMAIN_MODEL_VERSION`,
so an index built with an older model can be detected and rebuilt.
"""

from rkgk.domain.agents import StructuredOutputAgent, StructuredOutputAgentError
from rkgk.domain.embedders import Embedder, EmbedderError
from rkgk.domain.models.base import SLUG_PATTERN, Entity, Slug
from rkgk.domain.models.chunk import CHUNK_ID_PATTERN, Chunk
from rkgk.domain.models.concept_normalization import (
    CONCEPT_NORMALIZATION_SCHEMA_VERSION,
    ConceptNormalization,
    ConceptNormalizationIssue,
    ConceptNormalizationRun,
    ConceptNormalizationValidationError,
    GeneralKnowledgeEdge,
    LocalConceptRef,
    MissingPaperExtractionsError,
    NormalizedConcept,
    build_concept_normalization_schema,
)
from rkgk.domain.models.embedding import EmbeddedItem, EmbeddedItemKind, EmbeddingTable
from rkgk.domain.models.graph import (
    ChunkEvidence,
    Concept,
    ConceptEdge,
    EvidenceResolutionError,
    KnowledgeGraph,
    PaperConceptEdge,
    UnresolvedEvidence,
)
from rkgk.domain.models.manifest import INDEX_SCHEMA_VERSION, IndexBuildRun, IndexManifest
from rkgk.domain.models.paper import (
    MARKER_PATTERN,
    MarkerKind,
    Page,
    PageMarker,
    Paper,
    PaperIndexEntry,
    PaperMeta,
    PaperPreprocessInfo,
    build_paper_dir_name,
    parse_page,
)
from rkgk.domain.models.paper_extraction import (
    EXTRACTION_SCHEMA_VERSION,
    LOCAL_CONCEPT_ID_PATTERN,
    ExtractedConcept,
    ExtractedConceptEdge,
    ExtractedPaperConceptEdge,
    LocalConceptId,
    PageEvidence,
    PaperExtraction,
    PaperExtractionIssue,
    PaperExtractionMismatchError,
    PaperExtractionRun,
    PaperExtractionValidationError,
    build_paper_extraction_schema,
)
from rkgk.domain.models.search import (
    DEFAULT_TOP_K,
    ConceptHop,
    PaperCandidate,
    PaperHits,
    SearchConfig,
    SearchHit,
    SearchResult,
    TraversalPath,
)
from rkgk.domain.models.vocabulary import (
    ConceptRelationSpec,
    ConceptRelationType,
    ConceptType,
    ConceptTypeSpec,
    Origin,
    OriginSpec,
    PaperConceptRelation,
    RelationSpec,
    describe_vocabulary,
    traversable_concept_relations,
    traversable_concept_types,
    traversable_paper_relations,
)
from rkgk.domain.prompts.concept_normalization.builder import build_concept_normalization_prompt
from rkgk.domain.prompts.paper_extraction.builder import build_paper_extraction_prompt
from rkgk.domain.repositories.concept_normalization import (
    ConceptNormalizationArtifactInvalidError,
    ConceptNormalizationArtifactUnreadableError,
    ConceptNormalizationNotFoundError,
    ConceptNormalizationRepository,
    ConceptNormalizationRepositoryError,
)
from rkgk.domain.repositories.index import (
    IndexArtifactInvalidError,
    IndexArtifactUnreadableError,
    IndexIncompatibleError,
    IndexNotFoundError,
    IndexRepository,
    IndexRepositoryError,
)
from rkgk.domain.repositories.paper import (
    PaperArtifactInvalidError,
    PaperArtifactUnreadableError,
    PaperNotFoundError,
    PaperRepository,
    PaperRepositoryError,
)
from rkgk.domain.repositories.paper_extraction import (
    PaperExtractionArtifactInvalidError,
    PaperExtractionArtifactUnreadableError,
    PaperExtractionNotFoundError,
    PaperExtractionRepository,
    PaperExtractionRepositoryError,
)
from rkgk.domain.services.chunking import DEFAULT_MAX_TOKENS, chunk_paper
from rkgk.domain.services.concept_normalization import check_normalization_against_extractions
from rkgk.domain.services.embedding_items import build_embedding_items, concept_embedding_text
from rkgk.domain.services.evidence_resolver import find_chunk, resolve_extraction_evidence
from rkgk.domain.services.graph_builder import build_knowledge_graph, build_paper_node_id, to_networkx
from rkgk.domain.services.paper_extraction import check_extraction_against_paper, normalize_whitespace
from rkgk.domain.services.validation import format_error_path
from rkgk.domain.services.vector_search import compute_cosine_scores, search_vectors
from rkgk.domain.tokenizers import Tokenizer

DOMAIN_MODEL_VERSION = 1

__all__ = [
    "CHUNK_ID_PATTERN",
    "CONCEPT_NORMALIZATION_SCHEMA_VERSION",
    "DEFAULT_MAX_TOKENS",
    "DEFAULT_TOP_K",
    "DOMAIN_MODEL_VERSION",
    "EXTRACTION_SCHEMA_VERSION",
    "INDEX_SCHEMA_VERSION",
    "LOCAL_CONCEPT_ID_PATTERN",
    "MARKER_PATTERN",
    "SLUG_PATTERN",
    "Chunk",
    "ChunkEvidence",
    "Concept",
    "ConceptEdge",
    "ConceptHop",
    "ConceptNormalization",
    "ConceptNormalizationArtifactInvalidError",
    "ConceptNormalizationArtifactUnreadableError",
    "ConceptNormalizationIssue",
    "ConceptNormalizationNotFoundError",
    "ConceptNormalizationRepository",
    "ConceptNormalizationRepositoryError",
    "ConceptNormalizationRun",
    "ConceptNormalizationValidationError",
    "ConceptRelationSpec",
    "ConceptRelationType",
    "ConceptType",
    "ConceptTypeSpec",
    "EmbeddedItem",
    "EmbeddedItemKind",
    "Embedder",
    "EmbedderError",
    "EmbeddingTable",
    "Entity",
    "EvidenceResolutionError",
    "ExtractedConcept",
    "ExtractedConceptEdge",
    "ExtractedPaperConceptEdge",
    "GeneralKnowledgeEdge",
    "IndexArtifactInvalidError",
    "IndexArtifactUnreadableError",
    "IndexBuildRun",
    "IndexIncompatibleError",
    "IndexManifest",
    "IndexNotFoundError",
    "IndexRepository",
    "IndexRepositoryError",
    "KnowledgeGraph",
    "LocalConceptId",
    "LocalConceptRef",
    "MarkerKind",
    "MissingPaperExtractionsError",
    "NormalizedConcept",
    "Origin",
    "OriginSpec",
    "Page",
    "PageEvidence",
    "PageMarker",
    "Paper",
    "PaperArtifactInvalidError",
    "PaperArtifactUnreadableError",
    "PaperCandidate",
    "PaperConceptEdge",
    "PaperConceptRelation",
    "PaperExtraction",
    "PaperExtractionArtifactInvalidError",
    "PaperExtractionArtifactUnreadableError",
    "PaperExtractionIssue",
    "PaperExtractionMismatchError",
    "PaperExtractionNotFoundError",
    "PaperExtractionRepository",
    "PaperExtractionRepositoryError",
    "PaperExtractionRun",
    "PaperExtractionValidationError",
    "PaperHits",
    "PaperIndexEntry",
    "PaperMeta",
    "PaperNotFoundError",
    "PaperPreprocessInfo",
    "PaperRepository",
    "PaperRepositoryError",
    "RelationSpec",
    "SearchConfig",
    "SearchHit",
    "SearchResult",
    "Slug",
    "StructuredOutputAgent",
    "StructuredOutputAgentError",
    "Tokenizer",
    "TraversalPath",
    "UnresolvedEvidence",
    "build_concept_normalization_prompt",
    "build_concept_normalization_schema",
    "build_embedding_items",
    "build_knowledge_graph",
    "build_paper_dir_name",
    "build_paper_extraction_prompt",
    "build_paper_extraction_schema",
    "check_extraction_against_paper",
    "check_normalization_against_extractions",
    "chunk_paper",
    "compute_cosine_scores",
    "concept_embedding_text",
    "describe_vocabulary",
    "find_chunk",
    "format_error_path",
    "normalize_whitespace",
    "build_paper_node_id",
    "parse_page",
    "resolve_extraction_evidence",
    "search_vectors",
    "to_networkx",
    "traversable_concept_relations",
    "traversable_concept_types",
    "traversable_paper_relations",
]
